pull_request_rules:
  - name: add ros2 label
    description: If targeting an ROS2 branch, add the label
    conditions:
      - base = ros2
    actions:
      label:
        add:
          - ros2
  - name: no PRs against distro-specific branches
    description: PRs against branches like ros-humble are closed automatically. Unless they are a backport.
    conditions:
      - and:
        - base ~= ^ros2-[a-z]+$
        - not:
            head ~= ^backport\/.+$
    actions:
      close: 
        message: Please make all PRs against the `ros2` branch. They will be backported if possible.
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - label = automerge
      # we have to list all checks, apparently
      - check-success = Check licenses
      - check-success = Lint cppcheck
      - check-success = Lint cpplint
      - check-success = Lint flake8
      - check-success = Lint uncurstify
      - check-success = Lint xmllint
      - check-success ~= diagnostic_aggregator on [a-z]+
      - check-success ~= diagnostic_common_diagnostics on [a-z]+
      - check-success ~= diagnostic_remote_logging on [a-z]+
      # - check-success ~= diagnostic_topic_monitor on [a-z]+
      - check-success ~= diagnostic_updater on [a-z]+
      - check-success ~= self_test on [a-z]+
    actions:
      merge: