%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

%global __cmake_in_source_build 1

Name:           ros-humble-self-test
Version:        4.0.4
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS self_test package

License:        BSD-3-Clause
URL:            http://www.ros.org/wiki/self_test
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-humble-diagnostic-msgs
Requires:       ros-humble-diagnostic-updater
Requires:       ros-humble-rclcpp
Requires:       ros-humble-ros-workspace
BuildRequires:  ros-humble-ament-cmake
BuildRequires:  ros-humble-diagnostic-msgs
BuildRequires:  ros-humble-diagnostic-updater
BuildRequires:  ros-humble-rclcpp
BuildRequires:  ros-humble-ros-environment
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-humble-ament-cmake-gtest
BuildRequires:  ros-humble-ament-lint-auto
BuildRequires:  ros-humble-ament-lint-common
%endif

%description
self_test

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DAMENT_PREFIX_PATH="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Mon May 12 2025 Austin Hendrix <namniart@gmail.com> - 4.0.4-1
- Autogenerated by Bloom

* Thu Apr 03 2025 Austin Hendrix <namniart@gmail.com> - 4.0.3-1
- Autogenerated by Bloom

* Mon Feb 10 2025 Austin Hendrix <namniart@gmail.com> - 4.0.2-1
- Autogenerated by Bloom

* Fri Aug 02 2024 Austin Hendrix <namniart@gmail.com> - 4.0.0-1
- Autogenerated by Bloom

* Fri Mar 22 2024 Austin Hendrix <namniart@gmail.com> - 3.2.0-1
- Autogenerated by Bloom

* Fri Mar 24 2023 Austin Hendrix <namniart@gmail.com> - 3.1.2-1
- Autogenerated by Bloom

* Fri Mar 17 2023 Austin Hendrix <namniart@gmail.com> - 3.1.1-1
- Autogenerated by Bloom

* Thu Feb 23 2023 Austin Hendrix <namniart@gmail.com> - 3.1.0-2
- Autogenerated by Bloom

* Fri Jun 10 2022 Brice Rebsamen <brice.rebsamen@gmail.com> - 3.0.0-1
- Autogenerated by Bloom

* Tue Apr 19 2022 Brice Rebsamen <brice.rebsamen@gmail.com> - 2.1.3-3
- Autogenerated by Bloom

* Tue Feb 08 2022 Brice Rebsamen <brice.rebsamen@gmail.com> - 2.1.3-2
- Autogenerated by Bloom

