name: Lint diagnostics
on:
  pull_request:
  push:
    branches:
      - ros2
  schedule:
    # Run every week at 20:00 on Sunday
    - cron: "0 20 * * 0"

jobs:
  ament_lint:
    name: Lint ${{ matrix.linter }}
    strategy:
      fail-fast: false
      matrix:
        linter: [
            cppcheck,
            cpplint,
            flake8,
            # pep257, TODO: enable when we fixed
            # Error: diagnostic_common_diagnostics/diagnostic_common_diagnostics/ntp_monitor.py:113 in public method `ntp_diag`: D417: Missing argument descriptions in the docstring (argument(s) st are missing descriptions in 'ntp_diag' docstring)
            # using ros-rolling-ament-pep257 amd64 0.18.0-1noble.20240426.150718
            uncrustify,
            xmllint,
          ]
        include:
          - distro: rolling
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    env:
      AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: 1
    steps:
      - uses: actions/checkout@v1
      - uses: ros-tooling/setup-ros@master
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ros-tooling/action-ros-lint@master
        with:
          linter: ${{ matrix.linter }}
          package-name: |
            diagnostic_aggregator
            diagnostic_common_diagnostics
            diagnostic_updater
            self_test
